[tool.poetry]
name = "msapp"
version = "0.1.0"
description = "msa proteoform profiler"
authors = ["Yong Feng", "Lea Morschel"]
readme = "README.md"
packages = [{include = "msapp", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pytest = "^7.4.3"
argparse = "^1.4.0"
pysam = "^0.22.0"
numpy = "^1.26.1"
opencv-python = "^4.8.1.78"
matplotlib = "^3.8.0"
seaborn = "^0.13.0"
scipy = "^1.11.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
msapp = "msapp.cli:run"
